# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geotagged_imu.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13geotagged_imu.proto\x12\rgeotagged_imu\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x03\n\x0cGeoTaggedImu\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x64\x65ltaTs\x18\x02 \x01(\x02\x12\x37\n\timuChunks\x18\x03 \x03(\x0b\x32$.geotagged_imu.GeoTaggedImu.ImuChunk\x1a\x92\x01\n\x08Position\x12\r\n\x05valid\x18\x01 \x01(\x08\x12&\n\x02ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x01\x12\x0b\n\x03\x65ph\x18\x06 \x01(\x02\x12\x0b\n\x03\x65pv\x18\x07 \x01(\x02\x1aV\n\tImuSample\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0b\n\x03yaw\x18\x04 \x01(\x02\x12\r\n\x05pitch\x18\x05 \x01(\x02\x12\x0c\n\x04roll\x18\x06 \x01(\x02\x1a\xa2\x01\n\x08ImuChunk\x12&\n\x02ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x36\n\x08position\x18\x03 \x01(\x0b\x32$.geotagged_imu.GeoTaggedImu.Position\x12\x36\n\x07samples\x18\x04 \x03(\x0b\x32%.geotagged_imu.GeoTaggedImu.ImuSampleB\x11Z\x0f./geotagged_imub\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geotagged_imu_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\017./geotagged_imu'
  _globals['_GEOTAGGEDIMU']._serialized_start=72
  _globals['_GEOTAGGEDIMU']._serialized_end=574
  _globals['_GEOTAGGEDIMU_POSITION']._serialized_start=175
  _globals['_GEOTAGGEDIMU_POSITION']._serialized_end=321
  _globals['_GEOTAGGEDIMU_IMUSAMPLE']._serialized_start=323
  _globals['_GEOTAGGEDIMU_IMUSAMPLE']._serialized_end=409
  _globals['_GEOTAGGEDIMU_IMUCHUNK']._serialized_start=412
  _globals['_GEOTAGGEDIMU_IMUCHUNK']._serialized_end=574
# @@protoc_insertion_point(module_scope)
