# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geotagged_accel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15geotagged_accel.proto\x12\x0fgeotagged_accel\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x03\n\x05\x43hunk\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x64\x65ltaTs\x18\x02 \x01(\x02\x12\x36\n\x0b\x61\x63\x63\x65lChunks\x18\x03 \x03(\x0b\x32!.geotagged_accel.Chunk.AccelChunk\x1aj\n\x08Position\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x01\x12\x0b\n\x03\x65ph\x18\x05 \x01(\x01\x12\x0b\n\x03\x65pv\x18\x06 \x01(\x01\x1a.\n\x0b\x41\x63\x63\x65lSample\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x1a\x9c\x01\n\nAccelChunk\x12&\n\x02ts\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\x08position\x18\x03 \x01(\x0b\x32\x1f.geotagged_accel.Chunk.Position\x12\x33\n\x07samples\x18\x04 \x03(\x0b\x32\".geotagged_accel.Chunk.AccelSampleB\x13Z\x11./geotagged_accelb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geotagged_accel_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021./geotagged_accel'
  _globals['_CHUNK']._serialized_start=76
  _globals['_CHUNK']._serialized_end=483
  _globals['_CHUNK_POSITION']._serialized_start=170
  _globals['_CHUNK_POSITION']._serialized_end=276
  _globals['_CHUNK_ACCELSAMPLE']._serialized_start=278
  _globals['_CHUNK_ACCELSAMPLE']._serialized_end=324
  _globals['_CHUNK_ACCELCHUNK']._serialized_start=327
  _globals['_CHUNK_ACCELCHUNK']._serialized_end=483
# @@protoc_insertion_point(module_scope)
